/*DROP TABLE IF EXISTS `Thema`;*/
CREATE TABLE `Thema` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Thema` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`Thema`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*DROP TABLE IF EXISTS `TopicTokenThema`;*/
CREATE TABLE `TopicTokenThema` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TopicTokenID` int(11) NOT NULL DEFAULT '1',
  `ThemaID` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (TopicTokenID,ThemaID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
