DROP TABLE IF EXISTS `metaMAAbwesenheit`;
CREATE TABLE `metaMAAbwesenheit` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MAAbwesenheitID` int(11) NOT NULL DEFAULT '1',
  `JahrID0` int(11) NOT NULL DEFAULT '16',
  `JahrID1` int(11) NOT NULL DEFAULT '16',
  `KWID0` int(11) NOT NULL DEFAULT '18',
  `KWID1` int(11) NOT NULL DEFAULT '18',
  `TagID0` int(11) NOT NULL DEFAULT '0',
  `TagID1` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`JahrID0`,`KWID0`,`TagID0`,`JahrID1`,`KWID1`,`TagID1`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

