DROP TABLE Leistung;
DROP TABLE TrainerOrtLeistung;
DROP TABLE PersonKlient;
DROP TABLE ClientBeziehung;
DROP TABLE Engagement;
DROP TABLE Klient;
DROP TABLE KlientAdresse;
DROP TABLE KlientBeziehung;
DROP TABLE KlientKurs;
DROP TABLE KlientVS;
DROP TABLE Kontingent;
DROP TABLE MA;
DROP TABLE MAAdresse;
DROP TABLE MAClient;
DROP TABLE MAKlient;
DROP TABLE MAKlientVS;
DROP TABLE PersonClient;
DROP TABLE Person;
DROP TABLE TelKlient;
RENAME TABLE AdresseProband TO ProbandAdresse;
ALTER TABLE ProbandAdresse MODIFY COLUMN AdresseID int(11) NOT NULL DEFAULT 1 AFTER ProbandID;
RENAME TABLE MailProband TO ProbandMail;
ALTER TABLE ProbandMail MODIFY COLUMN MailID int(11) NOT NULL DEFAULT 1 AFTER ProbandID;
