CREATE TABLE `Region` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Region` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`Region`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `Umkreis` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RegionID` int(11) NOT NULL DEFAULT 1,
  `OrtID` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`RegionID`,`OrtID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
