/*DROP TABLE IF EXISTS `TokenSubToken`;*/
CREATE TABLE `TokenSubToken` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TokenID` int(11) NOT NULL DEFAULT '1',
  `SubTokenID` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (TokenID,SubTokenID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*DROP TABLE IF EXISTS `SubToken`;*/
CREATE TABLE `SubToken` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TokenID` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`TokenID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
