/*DROP TABLE IF EXISTS `TopicToken`;*/
CREATE TABLE `TopicToken` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TopicID` int(11) NOT NULL DEFAULT '1',
  `TokenID` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (TopicID,TokenID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*DROP TABLE IF EXISTS `Token`;*/
CREATE TABLE `Token` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Token` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`Token`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*DROP TABLE IF EXISTS `Topic`;*/
CREATE TABLE `Topic` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Topic` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`Topic`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

