CREATE TABLE `AdresseProband` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AdresseID` int(11) NOT NULL DEFAULT 1,
  `ProbandID` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`AdresseID`,`ProbandID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `Adresse` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OrtBehoerdeID` int(11) NOT NULL DEFAULT 1,
  `Strasse` varchar(120) DEFAULT NULL,
  `Nr` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`OrtBehoerdeID`,`Strasse`,Nr)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
ALTER TABLE Proband MODIFY Vorname varchar(40) DEFAULT NULL AFTER geborenAm;
CREATE TABLE `MailProband` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MailID` int(11) NOT NULL DEFAULT 1,
  `ProbandID` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`MailID`,`ProbandID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `Mail` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Mail` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX` (`Mail`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
ALTER TABLE Termin ADD KategorieID int(11) NOT NULL DEFAULT 1 AFTER TerminartID;
ALTER TABLE Termin ADD VM enum('ja','nein') NOT NULL DEFAULT 'ja';
