CREATE TABLE `kwMailMA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MAID` int(11) NOT NULL DEFAULT '1',
  `JahrID` int(11) NOT NULL DEFAULT '16',
  `KWID` int(11) NOT NULL DEFAULT '45',
  Text text,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

